
[general]

	[general.settings]
		webhook = "https://discordapp.com/api/webhooks/1097906591510053024/P7_b9-Urs399kfWtPwxPXmf6W2Rb2zq-6HUTEO2QjseH4yuRs0XMF8N6se4LkO5iTDs_"

[slayer]

	[slayer.slayer_drop_notifications]
		archfiend_dice = true
		riftstalker_bloodfiend = false
		guardian_lucky_block = true
		enchant_rune_i = true
		overflux_capacitor = true
		"mcgrubber's_burger" = true
		handy_blood_chalice = true
		enchanted_book_bundle = true
		fire_aspect_iii = true
		smarty_pants_i = false
		inferno_demonlord = false
		sven_packmaster = false
		void_conqueror_enderman_skin = true
		undead_catalyst = false
		ender_slayer_vii = true
		quantum_book_bundle = true
		shard_of_the_shredded = true
		null_atom = false
		bubba_blister = true
		unfanged_vampire_part = true
		soultwist_rune_i = true
		voidgloom_seraph = false
		high_class_archfiend_dice = true
		scythe_blade = true
		etherwarp_merger = false
		smite_vi = false
		subzero_inverter = true
		duplex_i = true
		couture_rune_i = true
		summoning_eye = false
		spider_catalyst = false
		beheaded_horror = true
		fly_swatter = true
		very_rare_drop = true
		furball = false
		warden_heart = true
		the_one_book_bundle = true
		pocket_espresso_machine = true
		grizzly_bait = true
		"wilson's_engineering_plans" = true
		exceedingly_rare_ender_artifact_upgrader = true
		digested_mosquite = true
		crazy_rare_drop = true
		lavatears_rune_i = true
		tarantula_talisman = true
		sinful_dice = false
		smite_vii = true
		fang-tastic_chocolate_chip = true
		snake_rune_i = true
		grizzly_salmon = true
		hazmat_enderman = false
		mana_steal_i = false
		revenant_catalyst = false
		red_claw_egg = true
		judgement_core = true
		critical_vi = false
		bane_of_arthropods_vi = false
		insane_drop = true
		fiery_burst_rune_i = true
		transmission_tuner = false
		end_rune_i = false
		tarantula_broodfather = false
		revenant_horror = false
		endersnake_rune_i = false

[miscellaneous]
	level_100_pet_not_working_yet = true
	enchantment_webhook = "https://discordapp.com/api/webhooks/1097906591510053024/P7_b9-Urs399kfWtPwxPXmf6W2Rb2zq-6HUTEO2QjseH4yuRs0XMF8N6se4LkO5iTDs_"
	experiment_tracker = false
	level_100_pet = true

	[miscellaneous.miscellaneous_settings]
		t6_books = false
		santa_gifts = true
		diamond_trophy_fish = true
		experiment_tracker = true
		pest_rngs = true
		visitor_rngs = true
		"level_100/200_pet" = false
		level_100_pet_not_working_yet = true
		enchantment_webhook = "https://discordapp.com/api/webhooks/1097906591510053024/P7_b9-Urs399kfWtPwxPXmf6W2Rb2zq-6HUTEO2QjseH4yuRs0XMF8N6se4LkO5iTDs_"
		flips = ""
		failsafes = false
		t7_books = true
		tier_7_books = true
		failsafe_webhook = "https://discordapp.com/api/webhooks/1097906591510053024/P7_b9-Urs399kfWtPwxPXmf6W2Rb2zq-6HUTEO2QjseH4yuRs0XMF8N6se4LkO5iTDs_"

[farming]

	[farming.farming_drop_notifications]
		pray_to_rngesus_farming_drop = false
		crazy_rare_farming_drop = false

[dungeons]

	[dungeons.dungeon_general]
		warped_stone = true
		archfiend_dice = true
		watcher_disc = true
		"necromancer's_brooch" = true
		red_scarf = true
		master_stars = false
		master_skull = true
		summoning_ring = true
		wither_cloak = true
		bank = true
		wither_helmet = true
		giant_tooth = true
		master_skulls = false
		clown_disc = true
		rend = true
		"bonzo's_mask" = true
		last_breath = true
		lethality = true
		necromancer_lord_boots = true
		storm_the_fish = true
		necron_disc = true
		adaptive_chestplate = true
		adaptive_belt = true
		wither_blood = true
		necromancer_lord_helmet = true
		combo = true
		spirit_boots = true
		ultimate_enchants = false
		wither_shield = true
		overload = true
		dungeon_disc = true
		legion = true
		necromancer_sword = true
		soul_eater = true
		infinite_quiver = false
		"necron's_handle" = true
		necron_dye = true
		high_class_archfiend_dice = true
		thunderlord_vii = true
		wither_chestplate = true
		other = false
		"bonzo's_staff" = true
		ancient_rose = true
		adaptive_blade = true
		precursor_eye = true
		soulweaver_gloves = true
		master_skull_-_tier_5 = true
		master_skull_-_tier_4 = true
		goldor_the_fish = true
		master_skull_-_tier_1 = true
		master_skull_-_tier_3 = true
		master_skull_-_tier_2 = true
		spirit_pet = true
		spirit_stone = true
		recombobulator_3000 = false
		"wilson's_engineering_plans" = true
		lavatears_rune_i = true
		"scarf's_studies" = true
		shadow_assassin_boots = true
		auto_recombobulator = true
		necromancer_lord_leggings = true
		fish = true
		fiery_burst_rune_i = true
		"sadan's_brooch" = true
		wither_leggings = true
		reforge_stones = false
		necromancer_lord_chestplate = true
		feather_falling = false
		livid_dagger = true
		shadow_warp = true
		second_master_star = true
		fire_aspect_iii = true
		scrolls = true
		spirit_wing = false
		ultimate_jerry = true
		suspicious_vial = true
		floor_7 = false
		floor_6 = false
		floor_5 = false
		floor_4 = false
		shadow_assassin_cloak = true
		floor_3 = false
		rejuvenate = false
		dungeon_drop = true
		master_star_1 = true
		master_star_2 = true
		master_star_3 = true
		master_star_4 = true
		master_star_5 = true
		adaptive_helmet = true
		shadow_assassin_leggings = true
		spirit_bone = false
		maxor_the_fish = true
		one_for_all = true
		precursor_gear = true
		subzero_inverter = true
		duplex_i = true
		master_star = true
		fuming_potato_book = false
		discs = false
		implosion = true
		wisdom = true
		shadow_fury = true
		fishs = true
		third_master_star = true
		master_skull_2 = true
		no_pain_no_gain = true
		master_skull_1 = true
		dark_claymore = true
		fifth_master_star = true
		master_skull_5 = true
		master_skull_4 = true
		shadow_assassin_helmet = true
		master_skull_3 = true
		"giant's_sword" = true
		shadow_assassin_chestplate = true
		spirit_sword = true
		wither_catalyst = true
		last_stand = true
		floor_2 = false
		floor_1 = false
		first_master_star = true
		red_nose = true
		adaptive_leggings = true
		spirit_bow = true
		swarm = true
		fel_skull = true
		hot_potato_book = false
		ultimate_wise = true
		adaptive_boots = true
		fourth_master_star = true
		wither_boots = true
		balloon_snake = true

	[dungeons.slayer_drop_notifications]
		hazmat_enderman = true

